import Link from "next/link";
import { getTranslations } from "next-intl/server";
import { BookMarked, FileCheck2 } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { listSourcesPage, listDocumentTypes, listTags } from "@/modules/wiki/research-queries";
import { parseTagList } from "@/modules/wiki/lib/tags";
import { PageHeader } from "@/components/page-header";
import { NewSourceDialog } from "@/modules/wiki/components/new-source-dialog";
import { SourceFilters } from "@/modules/wiki/components/source-filters";
import { LibraryTools } from "@/modules/wiki/components/library-tools";
import { MetadataLookupDialog } from "@/modules/wiki/components/metadata-lookup-dialog";
import { PdfUpload } from "@/modules/wiki/components/pdf-upload";
import { listPdfDocumentsForSources } from "@/modules/wiki/pdf-queries";
import { SourceListActions } from "@/modules/wiki/components/source-list-actions";

export default async function SourcesPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; tag?: string; cursor?: string }> }) {
  const [, t, params] = await Promise.all([requireUser(), getTranslations("wiki"), searchParams]);
  const sourcePage = listSourcesPage({ query: params.q, status: params.status, tagId: params.tag, cursor: params.cursor }); const sources = sourcePage.items; const documentTypes = listDocumentTypes().map((item) => item.value); const tags = listTags();
  const pdfStatus = listPdfDocumentsForSources(sources.map((source) => source.id));
  return <div className="mx-auto max-w-7xl p-5 md:p-8"><PageHeader eyebrow={t("evidenceLibrary")} title={t("sources")} description={t("sourcesDescription")} actions={<><MetadataLookupDialog documentTypes={documentTypes} /><NewSourceDialog documentTypes={documentTypes} /></>} />
    <PdfUpload dropzone />
    <div className="my-4"><LibraryTools /></div>
    <SourceFilters key={`${params.q ?? ""}:${params.status ?? ""}:${params.tag ?? ""}`} initialQuery={params.q ?? ""} initialStatus={params.status ?? ""} initialTag={params.tag ?? ""} tags={tags} />
    {sources.length === 0 ? <div className="mt-6 grid min-h-64 place-items-center rounded-xl border border-dashed bg-muted/20 text-center"><div><BookMarked className="mx-auto mb-3 size-8 text-indigo-400" /><h2 className="font-medium">{t("noSources")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("noSourcesDescription")}</p></div></div> :
    <div className="mt-4 overflow-x-auto rounded-xl border"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/50 text-left text-[11px] tracking-wider text-muted-foreground uppercase"><tr><th className="px-3 py-2">{t("sourceTitle")}</th><th className="px-3 py-2">{t("contributors")}</th><th className="px-3 py-2">{t("year")}</th><th className="px-3 py-2">{t("sourceType")}</th><th className="px-3 py-2">{t("readingStatus")}</th><th className="px-3 py-2">PDF</th><th className="px-3 py-2 text-right">{t("evidence")}</th></tr></thead><tbody className="divide-y">{sources.map((source) => { const documents = pdfStatus.get(source.id) ?? []; const primary = documents.find((document) => document.role === "primary") ?? documents[0]; const sourceHref = primary?.status === "ready" ? `/wiki/sources/${source.id}/read/${primary.id}` : `/wiki/sources/${source.id}`; return <tr key={source.id} className="group hover:bg-indigo-50/50 dark:hover:bg-indigo-950/20"><td className="max-w-sm px-3 py-3"><Link href={sourceHref} className="font-medium group-hover:text-indigo-700 dark:group-hover:text-indigo-300">{source.title}</Link>{parseTagList(source.tags).length > 0 && <p className="mt-1 flex flex-wrap gap-1">{parseTagList(source.tags).map((tag) => <Link key={tag.id} href={`/wiki/tags/${tag.id}`} className="rounded-full bg-indigo-50 px-2 py-0.5 text-[10px] text-indigo-700 hover:bg-indigo-100 dark:bg-indigo-950 dark:text-indigo-200 dark:hover:bg-indigo-900">{tag.name}</Link>)}</p>}</td><td className="max-w-xs truncate px-3 py-3 text-muted-foreground">{source.contributors ? source.contributors.split(",").join(", ") : "—"}</td><td className="px-3 py-3 tabular-nums text-muted-foreground">{source.issuedDate.slice(0,4) || "—"}</td><td className="px-3 py-3 text-muted-foreground">{t(`sourceTypes.${source.type}`)}</td><td className="px-3 py-3"><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs text-indigo-700 dark:bg-indigo-950 dark:text-indigo-200">{t(`readingStatuses.${source.readingStatus}`)}</span></td><td className="px-3 py-3 text-xs">{primary ? primary.status === "ready" ? <Link className="font-medium text-indigo-600" href={`/wiki/sources/${source.id}/read/${primary.id}`}>{primary.pageCount} {t("pagesCount")}</Link> : <span className={primary.status === "failed" ? "text-destructive" : "text-muted-foreground"}>{t(`pdfStatuses.${primary.status}`)}</span> : "—"}</td><td className="px-3 py-3 text-right text-xs text-muted-foreground"><span title={t("citations")} className="inline-flex items-center gap-1"><BookMarked className="size-3.5" />{source.citationCount}</span><span title={t("attachments")} className="ml-3 inline-flex items-center gap-1"><FileCheck2 className="size-3.5" />{source.attachmentCount}</span><span className="ml-2 inline-flex align-middle"><SourceListActions sourceId={source.id} /></span></td></tr>; })}</tbody></table></div>}
    {sourcePage.nextCursor && <div className="mt-4 flex justify-end"><Link className="rounded-md border bg-background px-4 py-2 text-sm font-medium hover:bg-accent" href={`/wiki/sources?${new URLSearchParams({ ...(params.q ? { q: params.q } : {}), ...(params.status ? { status: params.status } : {}), ...(params.tag ? { tag: params.tag } : {}), cursor: sourcePage.nextCursor }).toString()}`}>{t("nextPage")}</Link></div>}
  </div>;
}
