import { readFileSync } from "node:fs";
import { strFromU8, strToU8, unzipSync, zipSync } from "fflate";
import { describe, expect, it } from "vitest";
import type { PresentationElement } from "./presentation";
import { importPresentationPptx } from "./presentation-pptx";
import { parsePptxHtml } from "./presentation-pptx-text";

// Generated by scripts/fixtures/make-import-sample.py (python-pptx, 16:9 = 12192000 × 6858000 EMU).
const sample = () => new Uint8Array(readFileSync(new URL("./__fixtures__/import-sample.pptx", import.meta.url)));
const PX = 960 / 12192000;
const load = async (bytes: Uint8Array = sample()) => {
  const result = await importPresentationPptx(bytes, "Sample");
  const frames = result.snapshot.elements.filter((element) => element.type === "frame" && !element.content.isGroup);
  const on = (slide: number) => result.snapshot.elements.filter((element) => element.parentId === frames[slide - 1].id);
  return { ...result, frames, on };
};
/** Asserts slide-relative geometry within ±2 % of the python-pptx EMU values. */
function expectBox(element: PresentationElement | undefined, frame: PresentationElement, emu: [number, number, number, number]) {
  expect(element).toBeDefined();
  const [x, y, width, height] = emu.map((value) => value * PX);
  const near = (actual: number, expected: number, scale: number) => expect(Math.abs(actual - expected)).toBeLessThanOrEqual(scale * 0.02);
  near(element!.x - frame.x, x, 960); near(element!.y - frame.y, y, 540);
  near(element!.width, width, width); near(element!.height, height, height);
}
const textOf = (elements: PresentationElement[], needle: string) => elements.find((element) => element.type === "text" && element.content.text.includes(needle)) as Extract<PresentationElement, { type: "text" }> | undefined;

describe("PowerPoint import through pptxtojson", () => {
  it("creates one 16:9 frame and stop per slide, named after the slide title", async () => {
    const { frames, snapshot, warnings } = await load();
    expect(frames.map((frame) => [frame.width, frame.height])).toEqual(Array(4).fill([960, 540]));
    expect(frames.map((frame) => frame.type === "frame" && frame.content.label)).toEqual(["Quarterly Review", "Roadmap", "Budget Overview", "Revenue by Quarter"]);
    expect(snapshot.steps.map((step) => step.elementId)).toEqual(frames.map((frame) => frame.id));
    expect(warnings.some((warning) => warning.code === "fallback")).toBe(false);
  });

  it("resolves placeholder geometry through layout and master instead of stacking at the origin", async () => {
    const { frames, on } = await load();
    const title = textOf(on(1), "Quarterly Review"), subtitle = textOf(on(1), "Management Platform 2026");
    expectBox(title, frames[0], [914400, 2130425, 10363200, 1470025]);
    expectBox(subtitle, frames[0], [1828800, 3886200, 8534400, 1752600]);
    expectBox(textOf(on(2), "Roadmap"), frames[1], [609600, 274638, 10972800, 1143000]);
    expectBox(textOf(on(2), "Launch presentation import"), frames[1], [609600, 1600200, 10972800, 4525963]);
    // Font sizes use the geometry factor: 44 pt titles on a 960 pt wide slide stay 44 px on a 960 px frame.
    expect(title!.content.fontSize).toBe(44);
    expect(title!.content.align).toBe("center");
    for (const element of [...on(1), ...on(2)]) if (element.type === "text") expect(element.content.fontSize).toBeGreaterThanOrEqual(18);
  });

  it("keeps bullets as separate paragraphs in one text box, with the nested bullet indented", async () => {
    const { on, warnings } = await load();
    const bodies = on(2).filter((element) => element.type === "text");
    expect(bodies).toHaveLength(2);
    const body = textOf(on(2), "Launch")!;
    expect(body.content.text.split("\n")).toEqual(["• Launch presentation import", "• Improve the canvas editor", " ◦ Frames as containers", "• Ship collaboration"]);
    expect(body.content.fontSize).toBe(32);
    expect(warnings).toContainEqual({ slide: 2, code: "fontSizes" });
  });

  it("preserves shape fill and stroke, images, and turns the table into grouped cells", async () => {
    const { frames, on, media, warnings, snapshot } = await load();
    const shape = on(3).find((element) => element.type === "shape");
    expectBox(shape, frames[2], [914400, 1828800, 2743200, 1828800]);
    expect(shape).toMatchObject({ content: { shape: "rect", fill: "#2e86de", stroke: "#1b4f72", strokeWidth: 1.5 } });
    expect(textOf(on(3), "Total 120k")).toMatchObject({ content: { color: "#ffffff", fontSize: 18 } });
    const image = on(3).find((element) => element.type === "image");
    expectBox(image, frames[2], [914400, 4114800, 914400, 914400]);
    expect(media).toHaveLength(1);
    expect(image?.type === "image" && image.content.attachmentId).toBe(media[0].key);
    const table = on(3).find((element) => element.type === "frame" && element.content.isGroup)!;
    expectBox(table, frames[2], [4572000, 1828800, 5486400, 1371600]);
    const cells = snapshot.elements.filter((element) => element.parentId === table.id && element.type === "text").map((element) => element.type === "text" && element.content.text);
    expect(cells).toEqual(["Item", "Q1", "Q2", "Staff", "40", "45", "Tools", "10", "12"]);
    expect(warnings).toContainEqual({ slide: 3, code: "table" });
  });

  it("maps the bar chart data and the speaker notes of slide 4", async () => {
    const { frames, on, snapshot } = await load();
    const chart = on(4).find((element) => element.type === "chart");
    expectBox(chart, frames[3], [1828800, 1828800, 7315200, 4114800]);
    expect(chart).toMatchObject({ content: { kind: "bar", title: "Revenue", data: [{ label: "Q1", value: 12 }, { label: "Q2", value: 18 }, { label: "Q3", value: 27 }, { label: "Q4", value: 21 }] } });
    expect(snapshot.steps.map((step) => step.notes)).toEqual(["", "", "", "Emphasise the Q3 growth.\nMention the new customers."]);
  });

  it("lists notes per slide instead of one generic sentence for every slide", async () => {
    const { warnings } = await load();
    expect(warnings).toEqual([{ slide: 2, code: "fontSizes" }, { slide: 3, code: "table" }]);
  });

  it("follows the presentation's slide order rather than the file numbering", async () => {
    const files = unzipSync(sample());
    const xml = strFromU8(files["ppt/presentation.xml"]);
    const ids = [...xml.matchAll(/<p:sldId [^>]*\/>/g)].map((match) => match[0]);
    files["ppt/presentation.xml"] = strToU8(xml.replace(ids.join(""), [ids[3], ids[0], ids[1], ids[2]].join("")));
    const { frames } = await load(zipSync(files));
    expect(frames.map((frame) => frame.type === "frame" && frame.content.label)).toEqual(["Revenue by Quarter", "Quarterly Review", "Roadmap", "Budget Overview"]);
  });

  it("applies the XML entity limit to every part before the parser sees the package", async () => {
    const files = unzipSync(sample());
    files["ppt/unused.xml"] = strToU8('<!DOCTYPE x [<!ENTITY a "b">]><x/>');
    await expect(importPresentationPptx(zipSync(files), "Deck")).rejects.toThrow(/entities/);
  });

  it("falls back to the direct reader when the full parser cannot read a package", async () => {
    const files = unzipSync(sample());
    for (const name of Object.keys(files)) if (name.startsWith("ppt/slides/_rels/")) delete files[name];
    const { frames, warnings } = await load(zipSync(files));
    expect(frames).toHaveLength(4);
    expect(warnings[0]).toEqual({ slide: 0, code: "fallback" });
  });
});

describe("pptxtojson text HTML", () => {
  it("reads explicit lists, styles, links and entities without interpreting markup in text", () => {
    const [first, second] = parsePptxHtml('<ul><li><p style="text-align: right;"><span style="font-weight: bold;color: #FF0000;font-size: 20pt;">A&nbsp;&lt;b&gt;</span></p></li><ul><li><p style="text-align: left;"><span style="font-style: italic;"><a href="https://example.com" target="_blank">x</a></span></p></li></ul></ul>');
    expect(first).toMatchObject({ align: "right", list: "bullet", listDepth: 0, runs: [{ text: "A <b>", bold: true, color: "#ff0000", sizePt: 20 }] });
    expect(second).toMatchObject({ list: "bullet", listDepth: 1, runs: [{ text: "x", italic: true, href: "https://example.com" }] });
  });
});
