import { expect, test } from "@playwright/test";

test("wiki home persists customization and double Shift switches documents", async ({ page }) => {
  test.setTimeout(180_000);
  const credentials = { username: "wiki-home", password: "super-secret-1" };
  let response = await page.request.post("/api/auth/sign-up/email", { data: { ...credentials, displayUsername: "wiki-home", name: "Wiki Home", email: "wiki-home@example.com" } });
  if (!response.ok()) response = await page.request.post("/api/auth/sign-in/username", { data: credentials });
  if (!response.ok()) response = await page.request.post("/api/auth/sign-in/username", { data: { username: "reliable-editor", password: credentials.password } });
  expect(response.ok()).toBe(true);
  await page.goto("/wiki");
  const home = page.getByTestId("wiki-home");
  await expect(home.getByRole("navigation", { name: "Wiki-Bibliotheken" }).getByRole("link")).toHaveCount(3);
  await page.keyboard.press("Shift");
  await home.getByRole("heading", { name: "Dein Wiki", exact: true }).click();
  await page.keyboard.press("Shift");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await home.getByRole("button", { name: "Dokument schreiben", exact: true }).click();
  await page.waitForURL(/\/wiki\/pages\/.+/);
  const documentUrl = page.url();
  const editor = page.locator(".ProseMirror");
  await expect(editor).toHaveAttribute("contenteditable", "true");
  await editor.fill("Navigation test content");
  await page.keyboard.press("Shift"); await page.keyboard.press("Shift");
  const switcher = page.getByRole("dialog", { name: "Wiki-Inhalt öffnen", exact: true });
  const commands = page.getByRole("dialog", { name: "Befehl suchen", exact: true });
  await expect(commands.getByRole("combobox")).toBeFocused();
  await expect(switcher).toHaveCount(0);
  await commands.getByRole("combobox").press("Escape");
  await expect(editor).toBeFocused();
  await page.getByRole("button", { name: "Wiki-Inhalt öffnen", exact: true }).click();
  await expect(switcher.getByRole("combobox")).toBeFocused();
  await expect(switcher.getByRole("option").first()).toBeVisible();
  await switcher.getByRole("combobox").press("Escape");
  await expect(switcher).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Wiki-Inhalt öffnen", exact: true })).toBeFocused();
  await page.goto("/wiki");
  await expect(home.locator('[data-wiki-section="recent"] a').first()).toHaveAttribute("href", new URL(documentUrl).pathname);
  await home.locator('[data-wiki-section="document"]').getByRole("button", { name: /anheften$/ }).first().click();
  await expect(home.locator('[data-wiki-section="pinned"] a')).toHaveCount(1);
  await home.getByRole("button", { name: "Startseite anpassen" }).click();
  const settings = page.getByRole("dialog", { name: "Startseite anpassen" });
  await page.keyboard.press("Shift"); await page.keyboard.press("Shift");
  await expect(switcher).toHaveCount(0);
  await expect(settings).toBeVisible();
  await settings.getByRole("checkbox", { name: "Quellen", exact: true }).uncheck();
  await settings.getByRole("checkbox", { name: "Kompakte Listen" }).check();
  await settings.getByRole("button", { name: "Angeheftet nach oben" }).click();
  await settings.getByRole("button", { name: "Fertig" }).click();
  await page.reload();
  await expect(home.locator('[data-wiki-section="source"]')).toHaveCount(0);
  await expect(home.locator('[data-wiki-section="pinned"] a')).toHaveCount(1);
  await expect(home.locator('[data-wiki-section]')).toHaveCount(4);
  await expect(home.locator('[data-wiki-section]').nth(1)).toHaveAttribute("data-wiki-section", "pinned");
  await page.keyboard.press("Shift"); await page.keyboard.press("Shift");
  await expect(switcher.getByRole("combobox")).toBeFocused();
  await expect(switcher.getByRole("option").first()).toBeVisible();
  await switcher.getByRole("combobox").press("Enter");
  await expect(page).toHaveURL(documentUrl);
  await page.goto("/wiki");
  await page.setViewportSize({ width: 360, height: 800 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await home.getByRole("button", { name: /Dokumente, Quellen, Präsentationen suchen/ }).click();
  await expect(switcher.getByRole("combobox")).toBeFocused();
  await switcher.getByRole("combobox").fill("definitely-no-wiki-content-xyz");
  await switcher.getByRole("button", { name: "Präsentationen", exact: true }).click();
  await expect(switcher.getByRole("status")).toHaveText("Keine passenden Inhalte.");
  await switcher.getByRole("combobox").press("Escape");
  await page.goto("/calendar");
  await page.getByRole("button", { name: "Filter", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Filter", exact: true })).toBeVisible();
  await page.keyboard.press("Shift"); await page.keyboard.press("Shift");
  await expect(switcher).toHaveCount(0);
  await page.getByRole("dialog", { name: "Filter", exact: true }).getByRole("button", { name: "Fertig" }).click();
  await expect(page.getByRole("dialog", { name: "Filter", exact: true })).toHaveCount(0);
  await page.keyboard.press("Shift"); await page.keyboard.press("Shift");
  await expect(switcher.getByRole("combobox")).toBeFocused();
  await switcher.getByRole("combobox").fill("Projekte");
  await switcher.getByRole("button", { name: "App-Bereiche", exact: true }).click();
  await expect(switcher.getByRole("option", { name: /Projekte/ })).toBeVisible();
  await switcher.getByRole("combobox").press("Enter");
  await expect(page).toHaveURL(/\/projects$/);
});
